image: docker:git

services:
  - docker:dind

variables:
  DOCKER_HOST: "tcp://localhost:2375"

stages:
  - build

build:
  stage: build
  script:
    - echo "Hello world!"
    - VERSION="$(cat VERSION)"
    - REGISTRY="registry.thuault.com"
    - IMAGE="website/blog"
    - git submodule init
    - git submodule update
    - ls -la *
    - docker build -t $REGISTRY/$IMAGE:$VERSION -t $REGISTRY/$IMAGE:latest .
  only:
    - master
