image: docker:latest

services:
  - docker:dind

stages:
  - build

build:
  stage: build
  script:
    - echo "Hello world!"
    - ls -la
    - VERSION="$(cat VERSION)"
    - REGISTRY="registry.thuault.com"
    - IMAGE="website/blog"
    - docker build -t $REGISTRY/$IMAGE:$VERSION -t $REGISTRY/$IMAGE:latest .
  only:
    - master
